package com.wwz.cli.core.handler;

import com.wwz.cli.core.command.CommandHolder;
import com.wwz.cli.core.command.CommandSpec;

import java.util.function.Supplier;

/**
 * Reusable handler for common interactive-shell commands.
 *
 * <p>Applications still own their command enum, so this class asks the application to
 * provide enum values for empty input, help, clear, and unknown command handling. The
 * help text itself is provided lazily through a supplier so it can be generated by the
 * application's own help printer.</p>
 */
public class SystemCommandHandlerSupport<C extends CommandSpec> extends CommandHandlerSupport<C> {

    /**
     * ANSI sequence used by common terminals to clear scrollback and move the cursor home.
     */
    public static final String ANSI_CLEAR_SCREEN = "\033[2J\033[3J\033[H";

    private final Supplier<String> helpSupplier;

    /**
     * Registers built-in system command operations.
     */
    public SystemCommandHandlerSupport(C emptyCommand,
                                       C helpCommand,
                                       C clearCommand,
                                       C unknownCommand,
                                       Supplier<String> helpSupplier) {
        this.helpSupplier = helpSupplier;
        register(emptyCommand, this::empty);
        register(helpCommand, this::help);
        register(clearCommand, this::clear);
        register(unknownCommand, this::unknown);
    }

    private String empty(C command, CommandHolder commandHolder) {
        return "";
    }

    private String help(C command, CommandHolder commandHolder) {
        return helpSupplier.get();
    }

    private String clear(C command, CommandHolder commandHolder) {
        return ANSI_CLEAR_SCREEN;
    }

    private String unknown(C command, CommandHolder commandHolder) {
        return "未知命令：" + commandHolder.getName() + "，输入 help 查看支持的命令";
    }
}
